### ISSUE TITLE
Multiple faces issue

### ISSUE THREAD

**Issue by littleironical** [Nishant2907/Godseye#9] opened 2020-10-05 22:24 UTC
As we are doing this code using images which has only one person's face, 
**what if an image have more than one faces?**

Of which face of the two faces does our code do the encodings?

**Comment by nandita-jain** [comment] 2020-10-06 15:20
While using a picture with multiple faces it is not able to recognize multiple faces at time. The face which is left most is recognized.
![WhatsApp Image 2020-10-06 at 20 48 54](https://user-images.githubusercontent.com/65478174/95221921-93169c00-0815-11eb-9a65-eaf1e8263831.jpeg)

**Comment by Nishant2907** [comment] 2020-10-06 16:20
Found out that there is a key role function of the index number in the face recognition code. If the index is 0 then 1st face is recognized (from left) and if the index is set to 1, the second image is recognized.
![WhatsApp Image 2020-10-06 at 9 47 59 PM](https://user-images.githubusercontent.com/59792198/95229158-dd9c1680-081d-11eb-8e53-777b87e9b2f2.jpeg)

**Comment by Nishant2907** [comment] 2020-10-06 16:22
Above here, i have set the index 1 for both locations tags, after doing this only the faces got recognized and matched.
If the index of both location tags are different then also if the faces are same, they would not be recognized as same.

**Comment by littleironical** [comment] 2020-10-06 16:23
`johnnytestLocation = face_recognition.face_locations(imgJohnnytest)[1]`
`johnnytestEncode = face_recognition.face_encodings(imgJohnnytest)[1]`

We can use loop to check both the images

**Comment by nandita-jain** [comment] 2020-10-06 19:08
I have solved this issue
check pull request #12

**Comment by Nishant2907** [comment] 2020-10-06 19:08
Checked the code and has merged it in the main branch.

**Comment by Nishant2907** [comment] 2020-10-06 19:08
The issue is solved and has been closed.

**Closed as completed by Nishant2907** 2020-10-06 19:08 UTC
Labels: bug, enhancement, invalid
